print("Registration Form Successfully Created!") 
print("First Name: Jeevaaaaaa")
print("Last Name: Example")
print("Email: example@email.com")
print("Contact Number: 1234567890")
print("Password: ******")
print("Gender: Male")
